services:
  mysql:
    image: mysql:latest
    container_name: mysqlasd
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    restart: unless-stopped
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 2s
      retries: 10

  app:
    image: rob6723/bball-app
    container_name: app
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
       "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'

    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
#    command: bash -c "while !</dev/tcp/db/3306; do sleep 1; done && java -jar app.jar"
    restart: unless-stopped
